export const reviews = [
  {
    _id: "659f8521f3236c2f80cde439",
    name: "Tanmoy Das",
    email: "tanmoyy4060@gmail.com",
    designation: "Banker",
    rateus: "4.5",
    review: "Excellent service and friendly staff. Highly recommend!",
    image: "https://i.ibb.co/kQZtmdw/anik.jpg",
  },
  {
    _id: "659f8605f3236c2f80cde43b",
    name: "Sneha Roy",
    email: "sreyoshi780@gmail.com",
    designation: "HR Manager",
    rateus: "5",
    review: "The team did a fantastic job. My car has never run better!",
    image: "https://i.ibb.co/jWpVvy6/labo.webp",
  },
  {
    _id: "659f87e5f3236c2f80cde43d",
    name: "Ayon Bhattachargee",
    email: "ayon12@gmail.com",
    designation: "Marketing Executive",
    rateus: "5",
    review: "Great experience! The service was quick and efficient.",
    image: "https://i.ibb.co/17Wc8tp/pritom.webp",
  },
  {
    _id: "659f8853f3236c2f80cde43f",
    name: "Tamanna",
    email: "tama73468@gmail.com",
    designation: "Dentist",
    rateus: "4.5",
    review: "Very professional and reliable. Will definitely return!",
    image: "https://i.ibb.co/xDzSqD7/tonni.png",
  },
  {
    _id: "659f8913f3236c2f80cde441",
    name: "Rajib",
    email: "rajib@gmail.com",
    designation: "MERN Developer",
    rateus: "4",
    review: "Outstanding service! The team is very knowledgeable.",
    image: "https://i.ibb.co/YyhM9pb/Rajib.jpg",
  },
  {
    _id: "659f89acf3236c2f80cde443",
    name: "Alayana",
    email: "alayana@gmail.com",
    designation: "Software Engineer",
    rateus: "5",
    review: "Good service but could improve on response time.",
    image: "https://i.ibb.co/569K7ZW/Alayana.jpg",
  },
];
